[tool.poetry]
name = "aws-cli-tldr"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
aws-sam-cli = "^1.35.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^4.0.1"
mypy = "^0.910"
isort = "^5.10.1"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-mock = "^3.6.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
